// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Product struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Image         sql.NullString
	Price         decimal.Decimal
	StockQuantity int32
	CreatedAt     time.Time
	UserID        uuid.UUID
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
}
