// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products_queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name, description, image, price, stock_quantity, user_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, image, price, stock_quantity, created_at, user_id
`

type CreateProductParams struct {
	Name          string
	Description   string
	Image         sql.NullString
	Price         decimal.Decimal
	StockQuantity int32
	UserID        uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Price,
		arg.StockQuantity,
		arg.UserID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1 AND user_id = $2
`

type DeleteProductParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.UserID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, image, price, stock_quantity, created_at, user_id FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, image, price, stock_quantity, created_at, user_id FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.Price,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = $2,
    description = $3,
    image = $4,
    price = $5,
    stock_quantity = $6
WHERE id = $1 AND user_id = $7
RETURNING id, name, description, image, price, stock_quantity, created_at, user_id
`

type UpdateProductParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Image         sql.NullString
	Price         decimal.Decimal
	StockQuantity int32
	UserID        uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Price,
		arg.StockQuantity,
		arg.UserID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
